sudo:       required
language:   generic
services:   docker

# Docs of the options: https://github.com/Strauman/travis-latexbuild/tree/master#configuration-options
tex-config:
- tex-scheme=small
- push-type=none
- build-pattern=src/rubiks-notes.tex
#- latexmk-flags=-dvi -f
# Index of packages: http://ctan.mirrors.hoobly.com/systems/texlive/tlnet/archive/
- packages=tikz, rubik

script:
- docker pull strauman/travis-latexbuild:small # select small texlive scheme
- docker run --mount src=$TRAVIS_BUILD_DIR/,target=/repo,type=bind strauman/travis-latexbuild:small # also here